[package]
name = "s3-benchrunner-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
aws-config = { version= "1.1.4", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1.14.0"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.70"
serde_json = "1"
futures = "0.3.30"
env_logger = "0.9.0"
tracing = "0.1.37"

[dependencies.clap]
version = "~4.4"
features = ["derive"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.tracing-subscriber]
version = "0.3.5"
features = ["env-filter"]